stages:
  ingest:
    cmd: python3 src/ingest.py
    deps:
    - src/ingest.py
    params:
    - ingest.dcount
    outs:
    - data/prepared
  
  split:
    cmd: python3 src/split.py data/prepared data/split
    deps:
    - src/split.py
    - data/prepared
    params:
    - ingest.dcount
    outs:
    - data/split
  
  augment:
    cmd: python3 src/augment.py data/split data/augmented
    deps:
    - src/augment.py
    - data/split
    params:
    - ingest.dcount
    outs:
    - data/augmented
  
  train:
    cmd: python3 src/train.py data/split data/trained data/augmented
    deps:
    - src/train.py
    - data/split
    - data/augmented
    params:
    - ingest.dcount
    outs:
    - data/trained
  
  predict:
    cmd: python3 src/predict.py data/split data/predicted data/split
    deps:
    - src/predict.py
    - data/split
    params:
    - ingest.dcount
    outs:
    - data/predicted

  # transform:
  #   cmd: python3 src/transform.py data/prepared data/transformed
  #   deps:
  #   - src/transform.py
  #   - data/prepared
  #   params:
  #   - ingest.dcount
  #   outs:
  #   - data/transformed

  # predict:
  #   cmd: python3 src/predict.py data/prepared data/predictions data/store
  #   deps:
  #   - data/prepared
  #   - src/predict.py
  #   params:
  #   - ingest.dcount
  #   outs:
  #   - data/predictions
  
  # evaluate:
  #   cmd: python3 src/evaluate.py data/prepared data/transformed data/predictions data/evaluated data/store
  #   deps:
  #   - data/prepared
  #   - data/transformed
  #   - data/predictions
  #   params:
  #   - ingest.dcount
  #   outs:
  #   - data/evaluated
