stages:
  ingest:
    cmd: python3 src/ingest.py
    deps:
    - src/ingest.py
    params:
    - ingest.dcount
    outs:
    - data/prepared
  
  split:
    cmd: python3 src/split.py data/prepared data/split
    deps:
    - src/split.py
    - data/prepared
    params:
    - ingest.dcount
    outs:
    - data/split
  
  augment:
    cmd: python3 src/augment.py data/split data/augmented
    deps:
    - src/augment.py
    - data/split
    params:
    - ingest.dcount
    outs:
    - data/augmented
  
  train:
    cmd: python3 src/train.py data/split data/trained data/augmented
    deps:
    - src/train.py
    - data/split
    - data/augmented
    params:
    - ingest.dcount
    outs:
    - data/trained
  
  predict:
    cmd: python3 src/predict.py data/split data/predicted
    deps:
    - src/predict.py
    - data/split
    params:
    - ingest.dcount
    outs:
    - data/predicted


  compare:
    cmd: python3 src/compare.py data/trained data/predicted
    deps:
    - src/compare.py
    - data/predicted
    - data/trained
    params:
    - ingest.dcount
