stages:
  ingest:
    cmd: python3 src/ingest.py
    deps:
    - src/ingest.py
    params:
    - ingest.dcount
    outs:
    - data/prepared
  
  train:
    cmd: python3 src/train.py data/trained
    deps:
    - src/train.py
    - data/prepared
    params:
    - ingest.dcount
    outs:
    - data/trained

  # transform:
  #   cmd: python3 src/transform.py data/prepared data/transformed
  #   deps:
  #   - src/transform.py
  #   - data/prepared
  #   params:
  #   - ingest.dcount
  #   outs:
  #   - data/transformed

  # predict:
  #   cmd: python3 src/predict.py data/prepared data/predictions data/store
  #   deps:
  #   - data/prepared
  #   - src/predict.py
  #   params:
  #   - ingest.dcount
  #   outs:
  #   - data/predictions
  
  # evaluate:
  #   cmd: python3 src/evaluate.py data/prepared data/transformed data/predictions data/evaluated data/store
  #   deps:
  #   - data/prepared
  #   - data/transformed
  #   - data/predictions
  #   params:
  #   - ingest.dcount
  #   outs:
  #   - data/evaluated
