model: yolov5
ingest:
  dcount: 3
  dpath: dataset1.zip
class_id:
  person: 0
  person-like: 1
yolov5:
  weights: runs/train/exp3/weights/best.pt
  hyps:
    epochs: 5
    batch: 16
    optimizer: Adam
  outputs:
    train_dir: runs/train/
    val_dir: runs/val/
  version: 3
